import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { ChevronDown, ChevronRight, Snowflake, Bot, Search, RefreshCw, Zap, Container, GitBranch, ExternalLink, Presentation, Database, Waves, HardDrive, } from 'lucide-react';
const FEATURES = [
    {
        icon: Bot,
        name: 'Cortex Agent',
        description: 'AI coaching with claude-4-sonnet, tool use, and SSE streaming',
        docUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-agent',
        color: 'text-violet-600 bg-violet-50',
    },
    {
        icon: Search,
        name: 'Cortex Search',
        description: 'RAG over 15K call transcripts for grounded coaching answers',
        docUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-search/cortex-search-overview',
        color: 'text-blue-600 bg-blue-50',
    },
    {
        icon: RefreshCw,
        name: 'Dynamic Tables',
        description: 'Auto-refreshing leaderboard, KPIs, and call details — no ETL scheduling',
        docUrl: 'https://docs.snowflake.com/en/user-guide/dynamic-tables-about',
        color: 'text-emerald-600 bg-emerald-50',
    },
    {
        icon: Zap,
        name: 'Interactive Tables',
        description: 'Sub-second queries powering the coaching detail pages',
        docUrl: 'https://docs.snowflake.com/en/user-guide/interactive-tables',
        color: 'text-amber-600 bg-amber-50',
    },
    {
        icon: Container,
        name: 'SPCS',
        description: '3-container app deployed on Snowflake compute with OAuth SSO',
        docUrl: 'https://docs.snowflake.com/en/developer-guide/snowpark-container-services/overview',
        color: 'text-cyan-600 bg-cyan-50',
    },
    {
        icon: Database,
        name: 'Snowflake Postgres',
        description: 'Managed Postgres instance as the operational data source (16 tables)',
        docUrl: 'https://docs.snowflake.com/en/user-guide/postgres/overview',
        color: 'text-indigo-600 bg-indigo-50',
    },
    {
        icon: Waves,
        name: 'pg_lake',
        description: 'Replicates Postgres tables to Iceberg on S3 via pg_cron flush schedules',
        docUrl: 'https://docs.snowflake.com/en/user-guide/postgres/pg-lake',
        color: 'text-teal-600 bg-teal-50',
    },
    {
        icon: HardDrive,
        name: 'Iceberg Tables',
        description: 'Snowflake reads pg_lake Iceberg metadata from S3 — open table format',
        docUrl: 'https://docs.snowflake.com/en/user-guide/tables-iceberg',
        color: 'text-sky-600 bg-sky-50',
    },
    {
        icon: GitBranch,
        name: 'DCM',
        description: 'Schema-as-code — all Snowflake objects version-controlled',
        docUrl: 'https://docs.snowflake.com/en/developer-guide/database-change-management',
        color: 'text-rose-600 bg-rose-50',
    },
    {
        icon: Bot,
        name: 'Cortex Agent (NL Query)',
        description: 'Ask plain-English questions — the COACHING_AGENT uses semantic view + search tools to answer',
        docUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-agent',
        color: 'text-purple-600 bg-purple-50',
    },
];
const PRESENTER_NOTES = [
    {
        section: 'Dashboard Overview',
        points: [
            'KPI cards are powered by Dynamic Tables that auto-refresh — no cron jobs or Airflow DAGs',
            'The dealer breakdown table reads from the same Dynamic Table with sub-second latency',
            'All data is synthetic but follows realistic patterns from a real BDC operation',
        ],
    },
    {
        section: 'Agent Leaderboard',
        points: [
            'Rankings update automatically as new calls land in RAW tables — Dynamic Tables handle the refresh',
            'Scoring combines call score, sentiment, and conversion rate into a weighted composite',
        ],
    },
    {
        section: 'Agent Detail + AI Coaching',
        points: [
            'The coaching summary is generated by Cortex Agent (claude-4-sonnet) using the agent\'s recent call data',
            'Token usage and latency metadata are captured from the Cortex Agent response — show this to highlight observability',
            'The interactive chat uses Cortex Search to RAG over 15K transcripts, so recommendations cite specific calls',
            'SSE streaming delivers token-by-token responses — the UX feels like ChatGPT',
        ],
    },
    {
        section: 'Call Detail',
        points: [
            'Call detail pages use Interactive Tables for low-latency reads of individual records',
            'Transcript, AI summary, and score breakdown are all pre-computed and stored in Snowflake',
        ],
    },
    {
        section: 'Deployment & Infrastructure',
        points: [
            'The entire app runs on SPCS — no external hosting (Vercel, AWS, etc.) required',
            'DCM manages all Snowflake objects as code — tables, dynamic tables, search services, agents',
            'Single-command deploy with zero-downtime service updates via ALTER SERVICE',
        ],
    },
    {
        section: 'Data Pipeline (Postgres → Iceberg → Snowflake)',
        points: [
            'Snowflake Postgres is the operational database — 16 tables mirroring a real BDC system',
            'pg_lake extension writes Iceberg Parquet files to S3 via pg_cron flush schedules (every minute)',
            'Snowflake reads the Iceberg metadata directly — no COPY INTO or external ETL needed',
            'Pipeline page shows the full flow: Postgres → pg_lake → Iceberg → Dynamic Tables → Interactive Tables',
            'This is the "Snowflake as a platform" story — operational DB, data lake, and analytics in one place',
        ],
    },
    {
        section: 'Cortex Agent (NL Query)',
        points: [
            'The Agent page uses the same COACHING_AGENT with semantic view + search tools',
            'Users type plain-English questions and the agent queries data and returns answers',
            'This is the same Cortex Agent used for coaching — it has access to all BDC data',
            'Shows the power of a single agent handling both coaching AND analytics queries',
        ],
    },
];
const QUESTIONS_TO_ANTICIPATE = [
    'How does the Cortex Agent decide which transcripts to search?',
    'What happens when new calls are added — how fast do the dashboards update?',
    'Can this run on a standard warehouse or does it need SPCS?',
    'How much does the Cortex Agent cost per coaching summary?',
    'Why Postgres instead of just loading data directly into Snowflake?',
    'What is pg_lake and how does it compare to other CDC tools?',
    'Is the data real or synthetic?',
];
export default function SnowflakeFeatures() {
    const [expanded, setExpanded] = useState(false);
    const [notesExpanded, setNotesExpanded] = useState(false);
    return (_jsxs("div", { className: "bg-white rounded-xl border border-slate-200", style: { boxShadow: 'var(--card-shadow)' }, children: [_jsxs("button", { onClick: () => setExpanded(!expanded), className: "w-full flex items-center gap-3 px-5 py-3.5 text-left hover:bg-slate-50 transition-colors rounded-xl", children: [_jsx(Snowflake, { size: 18, className: "text-[#29B5E8] shrink-0" }), _jsx("span", { className: "text-sm font-semibold text-slate-700 flex-1", children: "Snowflake Features Powering This Demo" }), expanded ? (_jsx(ChevronDown, { size: 16, className: "text-slate-400" })) : (_jsx(ChevronRight, { size: 16, className: "text-slate-400" }))] }), expanded && (_jsxs("div", { className: "px-5 pb-5 space-y-5", children: [_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3", children: FEATURES.map((f) => (_jsxs("a", { href: f.docUrl, target: "_blank", rel: "noopener noreferrer", className: "group flex items-start gap-3 p-3.5 rounded-lg border border-slate-100 hover:border-slate-200 hover:bg-slate-50 transition-colors", children: [_jsx("div", { className: `p-2 rounded-lg shrink-0 ${f.color}`, children: _jsx(f.icon, { size: 16 }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "text-sm font-semibold text-slate-800", children: f.name }), _jsx(ExternalLink, { size: 11, className: "text-slate-300 group-hover:text-slate-500 transition-colors" })] }), _jsx("p", { className: "text-xs text-slate-500 mt-0.5 leading-relaxed", children: f.description })] })] }, f.name))) }), _jsxs("div", { className: "border-t border-slate-100 pt-4", children: [_jsxs("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    setNotesExpanded(!notesExpanded);
                                }, className: "flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 transition-colors", children: [_jsx(Presentation, { size: 14 }), _jsx("span", { className: "font-medium", children: "Presenter Notes" }), notesExpanded ? _jsx(ChevronDown, { size: 14 }) : _jsx(ChevronRight, { size: 14 })] }), notesExpanded && (_jsxs("div", { className: "mt-4 space-y-4", children: [PRESENTER_NOTES.map((section) => (_jsxs("div", { children: [_jsx("h4", { className: "text-xs font-semibold text-slate-600 uppercase tracking-wide mb-1.5", children: section.section }), _jsx("ul", { className: "space-y-1", children: section.points.map((point, i) => (_jsxs("li", { className: "text-xs text-slate-500 leading-relaxed flex gap-2", children: [_jsx("span", { className: "text-slate-300 shrink-0", children: "\u2022" }), _jsx("span", { children: point })] }, i))) })] }, section.section))), _jsxs("div", { className: "border-t border-slate-100 pt-3", children: [_jsx("h4", { className: "text-xs font-semibold text-slate-600 uppercase tracking-wide mb-1.5", children: "Questions to Anticipate" }), _jsx("ul", { className: "space-y-1", children: QUESTIONS_TO_ANTICIPATE.map((q, i) => (_jsxs("li", { className: "text-xs text-slate-500 leading-relaxed flex gap-2", children: [_jsx("span", { className: "text-slate-300 shrink-0", children: "?" }), _jsx("span", { children: q })] }, i))) })] })] }))] })] }))] }));
}
