import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import SentimentBadge from './SentimentBadge';
import { AlertCircle, CheckCircle2, MessageSquare } from 'lucide-react';
function formatOffset(seconds) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${String(s).padStart(2, '0')}`;
}
export default function TranscriptView({ transcript, callSummary, sentimentScore, sentimentLabel, disposition, followUpAction, customerObjections, }) {
    return (_jsxs("div", { className: "flex gap-6 items-start", children: [_jsx("div", { className: "flex-1 space-y-3 overflow-y-auto max-h-[600px] pr-1", children: transcript.map((turn, i) => {
                    const isAgent = turn.speaker === 'agent';
                    return (_jsx("div", { className: `flex ${isAgent ? 'justify-end' : 'justify-start'}`, children: _jsxs("div", { className: `max-w-[75%] ${isAgent ? 'items-end' : 'items-start'} flex flex-col gap-0.5`, children: [_jsxs("div", { className: "flex items-center gap-2", children: [!isAgent && (_jsx("span", { className: "text-xs text-slate-400 font-medium", children: turn.speaker_name })), _jsx("span", { className: "text-xs text-slate-400", children: formatOffset(turn.offset_seconds) }), isAgent && (_jsx("span", { className: "text-xs text-slate-400 font-medium", children: turn.speaker_name }))] }), _jsx("div", { className: `px-4 py-2.5 rounded-2xl text-sm leading-relaxed ${isAgent
                                        ? 'bg-blue-600 text-white rounded-tr-sm'
                                        : 'bg-white border border-slate-200 text-slate-700 rounded-tl-sm'}`, children: turn.text })] }) }, i));
                }) }), _jsx("div", { className: "w-72 shrink-0 space-y-4", children: _jsxs("div", { className: "bg-white rounded-xl border border-slate-200 p-4 space-y-3", children: [_jsxs("h3", { className: "text-sm font-semibold text-slate-700 flex items-center gap-2", children: [_jsx(MessageSquare, { size: 15, className: "text-blue-500" }), "AI Analysis"] }), sentimentScore !== null && (_jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 font-medium uppercase tracking-wide mb-1", children: "Sentiment" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(SentimentBadge, { score: sentimentScore }), sentimentLabel && (_jsx("span", { className: "text-xs text-slate-500", children: sentimentLabel }))] })] })), callSummary && (_jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 font-medium uppercase tracking-wide mb-1", children: "Summary" }), _jsx("p", { className: "text-xs text-slate-600 leading-relaxed", children: callSummary })] })), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 font-medium uppercase tracking-wide mb-1", children: "Disposition" }), _jsx("span", { className: "inline-block px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-xs", children: disposition })] }), followUpAction && (_jsxs("div", { children: [_jsxs("p", { className: "text-xs text-slate-400 font-medium uppercase tracking-wide mb-1 flex items-center gap-1", children: [_jsx(CheckCircle2, { size: 11, className: "text-emerald-500" }), " Follow-up"] }), _jsx("p", { className: "text-xs text-slate-600", children: followUpAction })] })), customerObjections && (_jsxs("div", { children: [_jsxs("p", { className: "text-xs text-slate-400 font-medium uppercase tracking-wide mb-1.5 flex items-center gap-1", children: [_jsx(AlertCircle, { size: 11, className: "text-amber-500" }), " Customer Objections"] }), _jsx("p", { className: "text-xs text-slate-600 leading-relaxed", children: customerObjections })] }))] }) })] }));
}
