import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertCircle, RefreshCw, CheckCircle2, Play, Loader2 } from 'lucide-react';
import { usePipelineLive, useRunTask } from '@/api/pipeline';
import PipelineFlow from '@/components/PipelineFlow';
export default function Pipeline() {
    const { data, isLoading, isError, refetch } = usePipelineLive();
    const runTask = useRunTask();
    if (isLoading) {
        return (_jsxs("div", { className: "p-6 space-y-5", children: [_jsx("div", { className: "h-6 w-48 bg-slate-200 rounded animate-pulse" }), _jsx("div", { className: "space-y-3", children: Array.from({ length: 5 }).map((_, i) => (_jsx("div", { className: "h-24 bg-white rounded-xl border border-slate-200 animate-pulse" }, i))) })] }));
    }
    if (isError || !data || data.error) {
        return (_jsxs("div", { className: "flex flex-col items-center justify-center h-80 gap-3 text-slate-500", children: [_jsx(AlertCircle, { size: 32, className: "text-red-400" }), _jsx("p", { children: "Failed to load pipeline metadata." }), data?.error && _jsx("p", { className: "text-xs text-slate-400", children: data.error }), _jsxs("button", { onClick: () => refetch(), className: "flex items-center gap-1.5 text-sm text-blue-600 hover:text-blue-800", children: [_jsx(RefreshCw, { size: 14 }), " Retry"] })] }));
    }
    const hasTasks = data.tasks.definitions.length > 0;
    return (_jsxs("div", { className: "p-6 space-y-5", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-bold text-slate-800", children: "Data Pipeline" }), _jsx("p", { className: "text-sm text-slate-500 mt-0.5", children: "Live Snowflake object metadata \u2014 every layer of this demo runs on Snowflake" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [hasTasks && (_jsxs("button", { onClick: () => runTask.mutate(), disabled: runTask.isPending, className: "flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors", children: [runTask.isPending ? (_jsx(Loader2, { size: 14, className: "animate-spin" })) : (_jsx(Play, { size: 14 })), "Generate New Data"] })), _jsxs("div", { className: "flex items-center gap-1.5 text-sm text-emerald-600", children: [_jsx(CheckCircle2, { size: 15 }), _jsx("span", { className: "font-medium", children: "Live" })] })] })] }), runTask.isSuccess && (_jsx("div", { className: "bg-emerald-50 border border-emerald-200 rounded-lg px-4 py-2 text-sm text-emerald-700", children: "Task triggered \u2014 new data will flow through the pipeline. Dynamic Tables will auto-refresh." })), runTask.isError && (_jsx("div", { className: "bg-red-50 border border-red-200 rounded-lg px-4 py-2 text-sm text-red-700", children: "Failed to trigger task. The daily generator task may not be created yet." })), _jsx(PipelineFlow, { data: data }), data.tasks.history.length > 0 && (_jsxs("div", { className: "bg-white rounded-xl border border-slate-200 p-5", style: { boxShadow: 'var(--card-shadow)' }, children: [_jsx("h3", { className: "text-sm font-semibold text-slate-700 mb-3", children: "Recent Task Runs" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-xs", children: [_jsx("thead", { children: _jsxs("tr", { className: "text-left text-slate-400 uppercase tracking-wide border-b border-slate-100", children: [_jsx("th", { className: "pb-2 pr-4 font-medium", children: "Task" }), _jsx("th", { className: "pb-2 pr-4 font-medium", children: "State" }), _jsx("th", { className: "pb-2 pr-4 font-medium", children: "Started" }), _jsx("th", { className: "pb-2 pr-4 font-medium", children: "Duration" }), _jsx("th", { className: "pb-2 font-medium", children: "Error" })] }) }), _jsx("tbody", { children: data.tasks.history.map((run, i) => (_jsxs("tr", { className: "border-b border-slate-50", children: [_jsx("td", { className: "py-2 pr-4 text-slate-700 font-medium", children: run.name }), _jsx("td", { className: "py-2 pr-4", children: _jsx("span", { className: `font-medium ${run.state === 'SUCCEEDED' ? 'text-emerald-600' :
                                                        run.state === 'FAILED' ? 'text-red-600' : 'text-amber-600'}`, children: run.state }) }), _jsx("td", { className: "py-2 pr-4 text-slate-500", children: run.started_at || '—' }), _jsx("td", { className: "py-2 pr-4 text-slate-500", children: run.duration_secs != null ? `${run.duration_secs}s` : '—' }), _jsx("td", { className: "py-2 text-red-500 truncate max-w-[200px]", children: run.error || '—' })] }, i))) })] }) })] })), _jsx("p", { className: "text-xs text-slate-400", children: "Auto-refreshes every 30 seconds \u00B7 Metadata queried live from Snowflake" })] }));
}
